services:
  postgres:
    image: postgres:14-alpine
    container_name: blog-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=blog
    ports:
      - "5432:5432"
    volumes:
      - ./data-db/:/var/lib/postgresql/data/

  redis:
    image: redis:7.4.1-alpine
    container_name: blog-redis
    # Set redis port for local only, do not set port on production
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: blog-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "miniopassword"
    volumes:
      - ./data-minio:/data
    command: server /data --console-address ":9001"

  api:
    image: blog-api
    container_name: blog-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://postgres:secret@postgres:5432/blog?sslmode=disable
      - MIGRATION_URL=file://db/migration
      - REDIS_ADDRESS=redis:6379
      - ENVIRONMENT=development
      - HTTP_SERVER_ADDRESS=0.0.0.0:8080
      - GRPC_SERVER_ADDRESS=0.0.0.0:9090
      - GIN_MODE=release
      - URL_FRONTEND=http://localhost:5173
      - TOKEN_SYMMETRIC_KEY=12345678901234567890123456789012
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY_ID=secret
      - MINIO_SECRET_ACCESS_KEY=ooZSAeYy5yYe1K9fySGJHLcJh3wyRa4K90vX04uz
      - MINIO_USE_SSL=false
      - MINIO_BUCKET_NAME=blog
      - MINIO_URL_RESULT=http://localhost:9000/blog/
      - EMAIL_SENDER_NAME=sender_name
      - EMAIL_SENDER_ADDRESS=yourself@gmail.com
      - EMAIL_SENDER_PASSWORD=yourselfgmailpassword
